project:
  type: website
  resources:
    - CNAME


website:
  title: "Juan's blog"
  description: "---"
  site-url: https://juantorofabra.com
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jtorofabra
      - icon: rss
        href: index.xml

format:
  html:
    theme:
      light: litera
      dark: darkly
    css: styles.css


